theme: jekyll-theme-leap-day
title: KapreSoft
description: The Java Blogger by Antonio Lagnada
show_downloads: false
show_google_ads: false
show_banner: false
google_analytics:
excerpt_separator: <!--excerpt-->

github:
  is_project_page: true
  owner_url: https://github.com/kapresoft/kapresoft.github.io
  owner_name: KapreSoft (Antonio Lagnada)

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from

exclude:  [".idea/"]
